version: "3.9"
services:
  core_api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:15.1-alpine
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_BASE_NAME}
    volumes:
      - db_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  db_volume:
    name: postgres_volume