version: "3.9"
services:
  core_api:
    build: .
    container_name: core_api
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    volumes:
      - app_volume:/app
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: 15.1-alpine
    restart: always
    container_name: postgres_database
    volumes:
      - db_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  app_volume:
    name: app_volume
  db_volume:
    name: postgres_volume
