"""group site_id added

Revision ID: 41dac5bb071e
Revises: aeb0afd7d0db
Create Date: 2023-01-10 20:02:46.843743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dac5bb071e'
down_revision = 'aeb0afd7d0db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('site_id', sa.Integer(), nullable=True, comment='Folder id on a site. Part of url.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'site_id')
    # ### end Alembic commands ###
