"""site_id removed

Revision ID: 602eebb89158
Revises: 41dac5bb071e
Create Date: 2023-01-12 09:42:10.191487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602eebb89158'
down_revision = '41dac5bb071e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Folder id on a site. Part of url.'))
    # ### end Alembic commands ###
