"""el_type removed!

Revision ID: 6a76f567033f
Revises: d797513eca62
Create Date: 2023-02-16 13:35:47.206405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a76f567033f'
down_revision = 'd797513eca62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'el_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('el_type', postgresql.ENUM('CATEGORY', 'SUBCATEGORY', 'GROUP', 'PRODUCT', name='eltype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
