"""Retailer name changed to enum

Revision ID: 7dea5c813d37
Revises: a0724d2b5879
Create Date: 2023-02-05 10:42:35.825490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dea5c813d37'
down_revision = 'a0724d2b5879'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retailer', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('retailer', 'home_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_retailer_name', table_name='retailer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_retailer_name', 'retailer', ['name'], unique=False)
    op.alter_column('retailer', 'home_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('retailer', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
