"""cascade

Revision ID: 90b0ed3913da
Revises: 840f057bb90b
Create Date: 2023-01-10 10:48:57.298203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b0ed3913da'
down_revision = '840f057bb90b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_line_product_id_fkey', 'price_line', type_='foreignkey')
    op.drop_constraint('price_line_retailer_id_fkey', 'price_line', type_='foreignkey')
    op.create_foreign_key(None, 'price_line', 'retailer', ['retailer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'price_line', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_line', type_='foreignkey')
    op.drop_constraint(None, 'price_line', type_='foreignkey')
    op.create_foreign_key('price_line_retailer_id_fkey', 'price_line', 'retailer', ['retailer_id'], ['id'])
    op.create_foreign_key('price_line_product_id_fkey', 'price_line', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
