"""PriceLine updated changed to time_created

Revision ID: 9c72002af4b4
Revises: ee4f70c06ac7
Create Date: 2023-02-05 10:07:13.017721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c72002af4b4'
down_revision = 'ee4f70c06ac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_line', sa.Column('time_created', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('price_line', 'updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_line', sa.Column('updated', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('price_line', 'time_created')
    # ### end Alembic commands ###
