"""PriceLine updated changed to date_created

Revision ID: a0724d2b5879
Revises: 9c72002af4b4
Create Date: 2023-02-05 10:09:41.837350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0724d2b5879'
down_revision = '9c72002af4b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_line', sa.Column('date_created', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('price_line', 'time_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_line', sa.Column('time_created', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('price_line', 'date_created')
    # ### end Alembic commands ###
