"""site_id removed

Revision ID: a47f33dfb1d8
Revises: 602eebb89158
Create Date: 2023-01-12 10:13:30.205894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47f33dfb1d8'
down_revision = '602eebb89158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
