"""product cascade

Revision ID: aeb0afd7d0db
Revises: 90b0ed3913da
Create Date: 2023-01-10 12:05:31.485675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb0afd7d0db'
down_revision = '90b0ed3913da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_line_product_id_fkey', 'price_line', type_='foreignkey')
    op.drop_constraint('price_line_retailer_id_fkey', 'price_line', type_='foreignkey')
    op.create_foreign_key(None, 'price_line', 'retailer', ['retailer_id'], ['id'])
    op.create_foreign_key(None, 'price_line', 'product', ['product_id'], ['id'])
    op.drop_constraint('product_parent_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'folder', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_parent_id_fkey', 'product', 'folder', ['parent_id'], ['id'])
    op.drop_constraint(None, 'price_line', type_='foreignkey')
    op.drop_constraint(None, 'price_line', type_='foreignkey')
    op.create_foreign_key('price_line_retailer_id_fkey', 'price_line', 'retailer', ['retailer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('price_line_product_id_fkey', 'price_line', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
