"""deprecated added to catalog

Revision ID: c8f8bf53f566
Revises: a47f33dfb1d8
Create Date: 2023-01-13 11:12:33.555410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f8bf53f566'
down_revision = 'a47f33dfb1d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('deprecated', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('deprecated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'deprecated')
    op.drop_column('folder', 'deprecated')
    # ### end Alembic commands ###
