"""removed UNIQUE from product name

Revision ID: d39695985f7f
Revises: c8f8bf53f566
Create Date: 2023-01-25 10:45:06.568292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39695985f7f'
down_revision = 'c8f8bf53f566'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_name', table_name='product')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_index('ix_product_name', 'product', ['name'], unique=False)
    # ### end Alembic commands ###
