"""db recreated

Revision ID: d797513eca62
Revises: 
Create Date: 2023-02-14 08:05:24.997731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd797513eca62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('el_type', sa.Enum('CATEGORY', 'SUBCATEGORY', 'GROUP', 'PRODUCT', name='eltype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_id'), 'folder', ['id'], unique=False)
    op.create_index(op.f('ix_folder_name'), 'folder', ['name'], unique=False)
    op.create_index(op.f('ix_folder_parent_id'), 'folder', ['parent_id'], unique=False)
    op.create_table('retailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('TAVRIA', 'SILPO', 'EPICENTR', name='retailername'), nullable=False),
    sa.Column('home_url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_id'), 'retailer', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('USER', 'ADMIN', 'SUPERUSER', name='usertype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('prime_cost', sa.Numeric(scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('price_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('retail_price', sa.Numeric(scale=2), nullable=True),
    sa.Column('promo_price', sa.Numeric(scale=2), nullable=True),
    sa.Column('date_created', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_line_id'), 'price_line', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_line_id'), table_name='price_line')
    op.drop_table('price_line')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_retailer_id'), table_name='retailer')
    op.drop_table('retailer')
    op.drop_index(op.f('ix_folder_parent_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_name'), table_name='folder')
    op.drop_index(op.f('ix_folder_id'), table_name='folder')
    op.drop_table('folder')
    # ### end Alembic commands ###
