"""updated added to PriceLine

Revision ID: ee4f70c06ac7
Revises: d39695985f7f
Create Date: 2023-02-03 09:20:18.867229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4f70c06ac7'
down_revision = 'd39695985f7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_line', sa.Column('updated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_line', 'updated')
    # ### end Alembic commands ###
