"""init

Revision ID: 9d3fdd264987
Revises: 
Create Date: 2022-12-02 17:36:59.881893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3fdd264987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('home_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_id'), 'retailer', ['id'], unique=False)
    op.create_index(op.f('ix_retailer_name'), 'retailer', ['name'], unique=False)
    op.create_table('subgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgroup_id'), 'subgroup', ['id'], unique=False)
    op.create_index(op.f('ix_subgroup_name'), 'subgroup', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('USER', 'ADMIN', 'SUPERUSER', name='usertype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.Column('prime_cost', sa.Numeric(scale=2), nullable=True),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('price_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('retail_price', sa.Numeric(scale=2), nullable=True),
    sa.Column('promo_price', sa.Numeric(scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_line_id'), 'price_line', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_line_id'), table_name='price_line')
    op.drop_table('price_line')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subgroup_name'), table_name='subgroup')
    op.drop_index(op.f('ix_subgroup_id'), table_name='subgroup')
    op.drop_table('subgroup')
    op.drop_index(op.f('ix_retailer_name'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_id'), table_name='retailer')
    op.drop_table('retailer')
    # ### end Alembic commands ###
